CREATE DATABASE IF NOT EXISTS zc_test;

CREATE TABLE zc_test.http_log_5m_x7 (
respStatus int(11) NOT NULL DEFAULT "0" COMMENT "响应状态码",
recordTimestamp bigint(20) NULL DEFAULT "0" COMMENT "日志记录时间戳，精确到秒",
reqMethod varchar(65533) NULL COMMENT "请求方法",
tenant varchar(65533) NULL COMMENT "租户 id",
uuId varchar(65533) NULL COMMENT "日志唯一 ID，云端生成。格式为：http_log-UUID",
v int(11) NOT NULL DEFAULT "0" COMMENT "数据标准的版本，当前是 1",
customer varchar(65533) NULL COMMENT "租户 id",
uploadTimestamp bigint(20) NOT NULL DEFAULT "0" COMMENT "日志上传时间戳，精确到秒",
insertTimestamp bigint(20) NOT NULL DEFAULT "0" COMMENT "日志入库时间戳，精确到秒",
recordTime varchar(65533) NULL COMMENT "日志记录时间字符串（本地时间）",
uploadTime varchar(65533) NULL COMMENT "日志上传时间字符串（本地时间）",
vendor varchar(65533) NULL COMMENT "设备厂商，使用英文",
productType varchar(65533) NULL COMMENT "直接上报端产品名称，使用英文",
productVer varchar(65533) NULL COMMENT "直接上报端产品版本号",
manage varchar(65533) NULL COMMENT "直接上报端设备 ID",
originProductType varchar(65533) NULL COMMENT "真实上报端产品，使用英文",
originProductVer varchar(65533) NULL COMMENT "真实上报端产品版本号，使用英文",
deviceId varchar(65533) NULL COMMENT "真实上报端设备 ID",
sessionId varchar(65533) NULL COMMENT "会话唯一 id（五元组 + 时间戳 + hash）",
httpId varchar(65533) NULL COMMENT "httpId，用来唯一标志（五元组 + 时间戳 + pipeline + hash）",
srcIp varchar(65533) NULL COMMENT "源 IP 地址",
srcPort int(11) NOT NULL DEFAULT "0" COMMENT "源端口",
srcMac varchar(65533) NULL COMMENT "源 mac 地址",
srcIpTag int(11) NOT NULL DEFAULT "0" COMMENT "0：内网 1：外网",
srcType int(11) NOT NULL DEFAULT "0" COMMENT "参考资产数据对接和资产分类规范中的 资产一级分类ID 服务器:001 等",
srcSubType int(11) NOT NULL DEFAULT "0" COMMENT "参考资产数据对接和资产分类规范中的 资产二级分类ID",
srcCountry varchar(65533) NULL COMMENT "源国家区域，必须英文",
srcProvince varchar(65533) NULL COMMENT "源省会区域，必须英文",
srcCity varchar(65533) NULL COMMENT "源城市区域，必须英文",
dstIp varchar(65533) NULL COMMENT "源 IP 地址",
dstPort int(11) NOT NULL DEFAULT "0" COMMENT "源端口",
dstMac varchar(65533) NULL COMMENT "源 mac 地址",
dstIpTag int(11) NOT NULL DEFAULT "0" COMMENT "源 ip 内外网 tag",
dstType int(11) NOT NULL DEFAULT "0" COMMENT "源资产分类",
dstSubType int(11) NOT NULL DEFAULT "0" COMMENT "源资产子类别",
dstCountry varchar(65533) NULL COMMENT "源国家区域，必须英文",
dstProvince varchar(65533) NULL COMMENT "源省会区域，必须英文",
dstCity varchar(65533) NULL COMMENT "源城市区域，必须英文",
uri varchar(65533) NULL COMMENT "uri",
url varchar(65533) NULL COMMENT "host + uri 的拼接",
userAgent varchar(65533) NULL COMMENT "客户端，",
xForwardedFor varchar(65533) NULL COMMENT "代理头部字段原始的内容，依次从头部字段里面获取（不区分大小写），如果有这个字段：",
reqContentType varchar(65533) NULL COMMENT "请求头部字段Conent-Type 里面的内容",
respContentType varchar(65533) NULL COMMENT "响应内容类型Conent-Type 里面的内容",
respServer varchar(65533) NULL COMMENT "响应头部字段Server 里面的内容",
duration int(11) NOT NULL DEFAULT "0" COMMENT "从请求到响应结束所用时间(单位：毫秒)，0 表示未知",
requestHead varchar(65533) NULL COMMENT "请求头",
responseHead varchar(65533) NULL COMMENT "响应头",
requestBody varchar(65533) NULL COMMENT "请求 body",
responseBody varchar(65533) NULL COMMENT "响应 body",
hostIp varchar(65533) NULL COMMENT "主机 ip",
hostIpValid varchar(65533) NULL COMMENT "主机 ip 是否在服务范围内",
moduleType varchar(65533) NULL COMMENT "固定值",
logType varchar(65533) NULL COMMENT "固定值",
manageIp varchar(65533) NULL COMMENT "",
deviceIp varchar(65533) NULL COMMENT "",
logSampled int(11) NULL COMMENT "",
logTraceInfo varchar(65533) NULL COMMENT "",
urlHash bigint(20) NULL COMMENT "",
encryptType int(11) NULL COMMENT "",
encPayloadType int(11) NULL COMMENT "",
encReqType int(11) NULL COMMENT "",
encRspType int(11) NULL COMMENT "",
srcAssetId varchar(65533) NULL COMMENT "",
dstAssetId varchar(65533) NULL COMMENT "",
srcIp_v4_int bigint(20) NULL DEFAULT "0" COMMENT "",
srcIp_v6_int largeint(40) NULL DEFAULT "0" COMMENT "",
dstIp_v4_int bigint(20) NULL DEFAULT "0" COMMENT "",
dstIp_v6_int largeint(40) NULL DEFAULT "0" COMMENT "",
hostIp_v4_int array<bigint(20)> NULL COMMENT "",
hostIp_v6_int array<largeint(40)> NULL COMMENT "",
cloudTs bigint(20) NULL COMMENT "",
srcRegionId varchar(65533) NULL COMMENT "",
dstRegionId varchar(65533) NULL COMMENT "",
extensions varchar(65533) NULL COMMENT "",
xForwardedForTag int(11) NULL COMMENT "",
reqBodyLen int(11) NULL COMMENT "",
respBodyLen int(11) NULL COMMENT "",
rawMsg varchar(65533) NULL COMMENT "",
greSrcIp array<varchar(65533)> NULL COMMENT "",
greDstIp array<varchar(65533)> NULL COMMENT "",
vxlanId array<int(11)> NULL COMMENT "",
vlanId array<int(11)> NULL COMMENT "",
mplsLabel array<int(11)> NULL COMMENT "",
tunnelProtocol array<varchar(65533)> NULL COMMENT "",
devUId int(11) NULL COMMENT "",
host varchar(65533) NULL COMMENT "",
reqDataGrade int(11) NULL COMMENT "",
reqDataClassifications array<varchar(65533)> NULL COMMENT "",
reqDataLabelIds array<varchar(65533)> NULL COMMENT "",
reqDataCounts array<int(11)> NULL COMMENT "",
reqDataValues varchar(65533) NULL COMMENT "",
respDataGrade int(11) NULL COMMENT "",
respDataClassifications array<varchar(65533)> NULL COMMENT "",
respDataLabelIds array<varchar(65533)> NULL COMMENT "",
respDataCounts array<int(11)> NULL COMMENT "",
respDataValues varchar(65533) NULL COMMENT "",
apiId varchar(65533) NULL COMMENT "",
apiName varchar(65533) NULL COMMENT "",
apiTags array<int(11)> NULL COMMENT "",
accountId varchar(65533) NULL COMMENT "",
accountName varchar(65533) NULL COMMENT "",
accountProofId varchar(65533) NULL COMMENT "",
xAppId varchar(65533) NULL COMMENT "",
xAppName varchar(65533) NULL COMMENT "",
xAppGroup varchar(65533) NULL COMMENT "",
xAppTags array<varchar(65533)> NULL COMMENT "",
xUserId varchar(65533) NULL COMMENT "",
xUserName varchar(65533) NULL COMMENT "",
xUserDomain varchar(65533) NULL COMMENT "",
xUserGroup varchar(65533) NULL COMMENT "",
xUserGroupId varchar(65533) NULL COMMENT "",
xUserSource varchar(65533) NULL COMMENT "",
xUserRoles array<varchar(65533)> NULL COMMENT "",
xUserTags array<varchar(65533)> NULL COMMENT "",
xUserProofId varchar(65533) NULL COMMENT "",
xffClientIp varchar(65533) NULL COMMENT "",
xffClientIpTag int(11) NULL COMMENT "",
xffClientIpType int(11) NULL COMMENT "",
xffClientIpSubType int(11) NULL COMMENT "",
xffClientIpAssetId varchar(65533) NULL COMMENT "",
xffClientIpRegionId varchar(65533) NULL COMMENT "",
responseBodyNoIndex varchar(65533) NULL COMMENT "不建索引的responseBody",
isResponseBodyIndex boolean NULL COMMENT "响应体索引标志: true(进responseBody), false(进responseBodyNoIndex), null未分类数据(进responseBody)",
bucketTimestamp bigint(20) NULL AS (floor(recordTimestamp / 600)) * 600 COMMENT "分钟级别int时间戳",
userDefineInt1 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt1') AS INT) COMMENT "",
userDefineInt2 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt2') AS INT) COMMENT "",
userDefineInt3 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt3') AS INT) COMMENT "",
userDefineInt4 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt4') AS INT) COMMENT "",
userDefineLong1 bigint(20) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineLong1') AS BIGINT) COMMENT "",
userDefineLong2 bigint(20) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineLong2') AS BIGINT) COMMENT "",
userDefineString1 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString1') AS VARCHAR) COMMENT "",
userDefineString2 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString2') AS VARCHAR) COMMENT "",
userDefineString3 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString3') AS VARCHAR) COMMENT "",
userDefineString4 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString4') AS VARCHAR) COMMENT "",
userDefineString5 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString5') AS VARCHAR) COMMENT "",
userDefineString6 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString6') AS VARCHAR) COMMENT "",
userDefineBool1 boolean NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineBool1') AS BOOLEAN) COMMENT "",
userDefineBool2 boolean NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineBool2') AS BOOLEAN) COMMENT "",
index_only varchar(1048576) NULL AS concat_ws('
', nullif(dstIp, ''), nullif(url, ''), nullif(requestHead, ''), nullif(requestBody, ''), nullif(responseHead, ''), nullif(responseBody, ''), nullif(deviceIp, ''), nullif(srcIp, ''), nullif(manageIp, '')) COMMENT "",
INDEX gIndex_index_only (index_only) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_dstIp (dstIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_url (url) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_requestHead (requestHead) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_reqMethod (reqMethod) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_hostIp (hostIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_deviceId (deviceId) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_deviceIp (deviceIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_srcIp (srcIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_userAgent (userAgent) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_xForwardedFor (xForwardedFor) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_requestBody (requestBody) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_manageIp (manageIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_manage (manage) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT ''
) ENGINE=OLAP
DUPLICATE KEY(respStatus, recordTimestamp, reqMethod)
PARTITION BY RANGE(from_unixtime(recordTimestamp))
(PARTITION p00 VALUES [("2026-08-28 06:00:00"), ("2026-08-28 06:05:00")),
PARTITION p01 VALUES [("2026-08-28 06:05:00"), ("2026-08-28 06:10:00")),
PARTITION p02 VALUES [("2026-08-28 06:10:00"), ("2026-08-28 06:15:00")),
PARTITION p03 VALUES [("2026-08-28 06:15:00"), ("2026-08-28 06:20:00")),
PARTITION p04 VALUES [("2026-08-28 06:20:00"), ("2026-08-28 06:25:00")),
PARTITION p05 VALUES [("2026-08-28 06:25:00"), ("2026-08-28 06:30:00")),
PARTITION p06 VALUES [("2026-08-28 06:30:00"), ("2026-08-28 06:35:00")))
DISTRIBUTED BY HASH(bucketTimestamp, srcIp_v4_int, dstIp) BUCKETS 1
ORDER BY(bucketTimestamp, srcIp_v4_int, respStatus, reqMethod)
PROPERTIES (
"bloom_filter_columns" = "dstIp_v4_int, dstIp_v6_int, dstIpTag, dstPort, insertTimestamp, logSampled, productType, respStatus, srcIp_v4_int, srcIp_v6_int, srcIpTag, srcPort, uploadTimestamp, uuId",
"compression" = "ZSTD(3)",
"fast_schema_evolution" = "true",
"replicated_storage" = "true",
"replication_num" = "1"
);
CREATE TABLE zc_test.http_log_35m_x1 (
respStatus int(11) NOT NULL DEFAULT "0" COMMENT "响应状态码",
recordTimestamp bigint(20) NULL DEFAULT "0" COMMENT "日志记录时间戳，精确到秒",
reqMethod varchar(65533) NULL COMMENT "请求方法",
tenant varchar(65533) NULL COMMENT "租户 id",
uuId varchar(65533) NULL COMMENT "日志唯一 ID，云端生成。格式为：http_log-UUID",
v int(11) NOT NULL DEFAULT "0" COMMENT "数据标准的版本，当前是 1",
customer varchar(65533) NULL COMMENT "租户 id",
uploadTimestamp bigint(20) NOT NULL DEFAULT "0" COMMENT "日志上传时间戳，精确到秒",
insertTimestamp bigint(20) NOT NULL DEFAULT "0" COMMENT "日志入库时间戳，精确到秒",
recordTime varchar(65533) NULL COMMENT "日志记录时间字符串（本地时间）",
uploadTime varchar(65533) NULL COMMENT "日志上传时间字符串（本地时间）",
vendor varchar(65533) NULL COMMENT "设备厂商，使用英文",
productType varchar(65533) NULL COMMENT "直接上报端产品名称，使用英文",
productVer varchar(65533) NULL COMMENT "直接上报端产品版本号",
manage varchar(65533) NULL COMMENT "直接上报端设备 ID",
originProductType varchar(65533) NULL COMMENT "真实上报端产品，使用英文",
originProductVer varchar(65533) NULL COMMENT "真实上报端产品版本号，使用英文",
deviceId varchar(65533) NULL COMMENT "真实上报端设备 ID",
sessionId varchar(65533) NULL COMMENT "会话唯一 id（五元组 + 时间戳 + hash）",
httpId varchar(65533) NULL COMMENT "httpId，用来唯一标志（五元组 + 时间戳 + pipeline + hash）",
srcIp varchar(65533) NULL COMMENT "源 IP 地址",
srcPort int(11) NOT NULL DEFAULT "0" COMMENT "源端口",
srcMac varchar(65533) NULL COMMENT "源 mac 地址",
srcIpTag int(11) NOT NULL DEFAULT "0" COMMENT "0：内网 1：外网",
srcType int(11) NOT NULL DEFAULT "0" COMMENT "参考资产数据对接和资产分类规范中的 资产一级分类ID 服务器:001 等",
srcSubType int(11) NOT NULL DEFAULT "0" COMMENT "参考资产数据对接和资产分类规范中的 资产二级分类ID",
srcCountry varchar(65533) NULL COMMENT "源国家区域，必须英文",
srcProvince varchar(65533) NULL COMMENT "源省会区域，必须英文",
srcCity varchar(65533) NULL COMMENT "源城市区域，必须英文",
dstIp varchar(65533) NULL COMMENT "源 IP 地址",
dstPort int(11) NOT NULL DEFAULT "0" COMMENT "源端口",
dstMac varchar(65533) NULL COMMENT "源 mac 地址",
dstIpTag int(11) NOT NULL DEFAULT "0" COMMENT "源 ip 内外网 tag",
dstType int(11) NOT NULL DEFAULT "0" COMMENT "源资产分类",
dstSubType int(11) NOT NULL DEFAULT "0" COMMENT "源资产子类别",
dstCountry varchar(65533) NULL COMMENT "源国家区域，必须英文",
dstProvince varchar(65533) NULL COMMENT "源省会区域，必须英文",
dstCity varchar(65533) NULL COMMENT "源城市区域，必须英文",
uri varchar(65533) NULL COMMENT "uri",
url varchar(65533) NULL COMMENT "host + uri 的拼接",
userAgent varchar(65533) NULL COMMENT "客户端，",
xForwardedFor varchar(65533) NULL COMMENT "代理头部字段原始的内容，依次从头部字段里面获取（不区分大小写），如果有这个字段：",
reqContentType varchar(65533) NULL COMMENT "请求头部字段Conent-Type 里面的内容",
respContentType varchar(65533) NULL COMMENT "响应内容类型Conent-Type 里面的内容",
respServer varchar(65533) NULL COMMENT "响应头部字段Server 里面的内容",
duration int(11) NOT NULL DEFAULT "0" COMMENT "从请求到响应结束所用时间(单位：毫秒)，0 表示未知",
requestHead varchar(65533) NULL COMMENT "请求头",
responseHead varchar(65533) NULL COMMENT "响应头",
requestBody varchar(65533) NULL COMMENT "请求 body",
responseBody varchar(65533) NULL COMMENT "响应 body",
hostIp varchar(65533) NULL COMMENT "主机 ip",
hostIpValid varchar(65533) NULL COMMENT "主机 ip 是否在服务范围内",
moduleType varchar(65533) NULL COMMENT "固定值",
logType varchar(65533) NULL COMMENT "固定值",
manageIp varchar(65533) NULL COMMENT "",
deviceIp varchar(65533) NULL COMMENT "",
logSampled int(11) NULL COMMENT "",
logTraceInfo varchar(65533) NULL COMMENT "",
urlHash bigint(20) NULL COMMENT "",
encryptType int(11) NULL COMMENT "",
encPayloadType int(11) NULL COMMENT "",
encReqType int(11) NULL COMMENT "",
encRspType int(11) NULL COMMENT "",
srcAssetId varchar(65533) NULL COMMENT "",
dstAssetId varchar(65533) NULL COMMENT "",
srcIp_v4_int bigint(20) NULL DEFAULT "0" COMMENT "",
srcIp_v6_int largeint(40) NULL DEFAULT "0" COMMENT "",
dstIp_v4_int bigint(20) NULL DEFAULT "0" COMMENT "",
dstIp_v6_int largeint(40) NULL DEFAULT "0" COMMENT "",
hostIp_v4_int array<bigint(20)> NULL COMMENT "",
hostIp_v6_int array<largeint(40)> NULL COMMENT "",
cloudTs bigint(20) NULL COMMENT "",
srcRegionId varchar(65533) NULL COMMENT "",
dstRegionId varchar(65533) NULL COMMENT "",
extensions varchar(65533) NULL COMMENT "",
xForwardedForTag int(11) NULL COMMENT "",
reqBodyLen int(11) NULL COMMENT "",
respBodyLen int(11) NULL COMMENT "",
rawMsg varchar(65533) NULL COMMENT "",
greSrcIp array<varchar(65533)> NULL COMMENT "",
greDstIp array<varchar(65533)> NULL COMMENT "",
vxlanId array<int(11)> NULL COMMENT "",
vlanId array<int(11)> NULL COMMENT "",
mplsLabel array<int(11)> NULL COMMENT "",
tunnelProtocol array<varchar(65533)> NULL COMMENT "",
devUId int(11) NULL COMMENT "",
host varchar(65533) NULL COMMENT "",
reqDataGrade int(11) NULL COMMENT "",
reqDataClassifications array<varchar(65533)> NULL COMMENT "",
reqDataLabelIds array<varchar(65533)> NULL COMMENT "",
reqDataCounts array<int(11)> NULL COMMENT "",
reqDataValues varchar(65533) NULL COMMENT "",
respDataGrade int(11) NULL COMMENT "",
respDataClassifications array<varchar(65533)> NULL COMMENT "",
respDataLabelIds array<varchar(65533)> NULL COMMENT "",
respDataCounts array<int(11)> NULL COMMENT "",
respDataValues varchar(65533) NULL COMMENT "",
apiId varchar(65533) NULL COMMENT "",
apiName varchar(65533) NULL COMMENT "",
apiTags array<int(11)> NULL COMMENT "",
accountId varchar(65533) NULL COMMENT "",
accountName varchar(65533) NULL COMMENT "",
accountProofId varchar(65533) NULL COMMENT "",
xAppId varchar(65533) NULL COMMENT "",
xAppName varchar(65533) NULL COMMENT "",
xAppGroup varchar(65533) NULL COMMENT "",
xAppTags array<varchar(65533)> NULL COMMENT "",
xUserId varchar(65533) NULL COMMENT "",
xUserName varchar(65533) NULL COMMENT "",
xUserDomain varchar(65533) NULL COMMENT "",
xUserGroup varchar(65533) NULL COMMENT "",
xUserGroupId varchar(65533) NULL COMMENT "",
xUserSource varchar(65533) NULL COMMENT "",
xUserRoles array<varchar(65533)> NULL COMMENT "",
xUserTags array<varchar(65533)> NULL COMMENT "",
xUserProofId varchar(65533) NULL COMMENT "",
xffClientIp varchar(65533) NULL COMMENT "",
xffClientIpTag int(11) NULL COMMENT "",
xffClientIpType int(11) NULL COMMENT "",
xffClientIpSubType int(11) NULL COMMENT "",
xffClientIpAssetId varchar(65533) NULL COMMENT "",
xffClientIpRegionId varchar(65533) NULL COMMENT "",
responseBodyNoIndex varchar(65533) NULL COMMENT "不建索引的responseBody",
isResponseBodyIndex boolean NULL COMMENT "响应体索引标志: true(进responseBody), false(进responseBodyNoIndex), null未分类数据(进responseBody)",
bucketTimestamp bigint(20) NULL AS (floor(recordTimestamp / 600)) * 600 COMMENT "分钟级别int时间戳",
userDefineInt1 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt1') AS INT) COMMENT "",
userDefineInt2 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt2') AS INT) COMMENT "",
userDefineInt3 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt3') AS INT) COMMENT "",
userDefineInt4 int(11) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineInt4') AS INT) COMMENT "",
userDefineLong1 bigint(20) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineLong1') AS BIGINT) COMMENT "",
userDefineLong2 bigint(20) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineLong2') AS BIGINT) COMMENT "",
userDefineString1 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString1') AS VARCHAR) COMMENT "",
userDefineString2 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString2') AS VARCHAR) COMMENT "",
userDefineString3 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString3') AS VARCHAR) COMMENT "",
userDefineString4 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString4') AS VARCHAR) COMMENT "",
userDefineString5 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString5') AS VARCHAR) COMMENT "",
userDefineString6 varchar(65533) NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineString6') AS VARCHAR) COMMENT "",
userDefineBool1 boolean NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineBool1') AS BOOLEAN) COMMENT "",
userDefineBool2 boolean NULL AS CAST((parse_json(extensions)->'$.userDefine.userDefineBool2') AS BOOLEAN) COMMENT "",
index_only varchar(1048576) NULL AS concat_ws('
', nullif(dstIp, ''), nullif(url, ''), nullif(requestHead, ''), nullif(requestBody, ''), nullif(responseHead, ''), nullif(responseBody, ''), nullif(deviceIp, ''), nullif(srcIp, ''), nullif(manageIp, '')) COMMENT "",
INDEX gIndex_index_only (index_only) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_dstIp (dstIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_url (url) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_requestHead (requestHead) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_reqMethod (reqMethod) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_hostIp (hostIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_deviceId (deviceId) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_deviceIp (deviceIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_srcIp (srcIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_userAgent (userAgent) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_xForwardedFor (xForwardedFor) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_requestBody (requestBody) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_manageIp (manageIp) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT '',
INDEX gIndex_manage (manage) USING NGRAMBF("bloom_filter_fpp" = "0.05", "case_sensitive" = "false", "gram_num" = "4", "granularity" = "15") COMMENT ''
) ENGINE=OLAP
DUPLICATE KEY(respStatus, recordTimestamp, reqMethod)
PARTITION BY RANGE(from_unixtime(recordTimestamp))
(PARTITION p_all VALUES [("2026-08-28 06:00:00"), ("2026-08-28 06:35:00")))
DISTRIBUTED BY HASH(bucketTimestamp, srcIp_v4_int, dstIp) BUCKETS 1
ORDER BY(bucketTimestamp, srcIp_v4_int, respStatus, reqMethod)
PROPERTIES (
"bloom_filter_columns" = "dstIp_v4_int, dstIp_v6_int, dstIpTag, dstPort, insertTimestamp, logSampled, productType, respStatus, srcIp_v4_int, srcIp_v6_int, srcIpTag, srcPort, uploadTimestamp, uuId",
"compression" = "ZSTD(3)",
"fast_schema_evolution" = "true",
"replicated_storage" = "true",
"replication_num" = "1"
);
